### ISSUE TITLE
Show commit details at the top of the hover popup

### ISSUE THREAD

**Issue by Arnesfield** [mk12/vscode-better-git-line-blame#15]
Currently, the commit details are shown at the bottom of the hover popup whenever a line has some code documentation.

1. The `.alias()` method has documentation and is shown first.

    ![vscode-better-git-line-blame code documentation](https://github.com/user-attachments/assets/ac3843be-cb58-4504-8378-d6769b79144a)

2. The commit details are shown at the bottom of the popup after the code documentation.

    ![vscode-better-git-line-blame commit details](https://github.com/user-attachments/assets/0fca77a0-4dd7-4cf3-96c9-087f701ee53d)

Using [GitLens](https://github.com/gitkraken/vscode-gitlens), it shows the details on the top instead like so:

1. Once the popup is shown, the first thing you see is the commit details.

    ![gitlens commit details](https://github.com/user-attachments/assets/771e2259-6886-4dae-b868-18bc37c89d7c)

2. Then the code documentation is shown after the commit details.

    ![gitlens code documentation](https://github.com/user-attachments/assets/ec8d37cd-c7f2-4fe2-a75e-d36cb0c57d6c)

I noticed that this happens on a method chain where the variable or method has code documentation.

To replicate, you can create a `git` repository and commit the following to a `.js` file:

```javascript
/** Variable documentation. */
const obj = {
  /** Method documentation. */
  func() {
    return this;
  }
};

obj // issue occurs here even with this comment
  .func() // also occurs here
  .func() // also occurs here
  .func(); // does not occur here
```

My suggestion would be to either:
- Show the commit details at the top, since the code documentation can be shown by hovering on the method itself.
- Or if possible, it would be nice to only show the commit details when hovering on the inline annotations.

Thanks for your work on the extension!

**Comment by mk12** [comment]
Hi @Arnesfield, thanks for the detailed report.

I don’t think the VS Code extension API offers direct control over the order of hovers from different extensions. The only thing I can find is https://github.com/microsoft/vscode/issues/152897.

If GitLens puts it on top reliably, I’m guessing it’s something to do with the extension loading order, or maybe the way they construct the range to attach to the end of the line. I’m not sure when I’ll have time but this is something I could investigate.

> Or if possible, it would be nice to only show the commit details when hovering on the inline annotations.

This should be the case by default, unless you set `betterGitLineBlame.annotateWholeLine` to true. The caveat to this, which you’re probably noticing in your example, is that the empty space between the last character and the inline annotation also counts. So if your cursor is at the end of the line touching this empty space it will show, but if it’s in the middle of the line it should not. I was not able to find a way to prevent this, but if anyone knows I would be happy to change it.

**Comment by Arnesfield** [comment]
Thanks for the response @mk12.

I don't mind the empty space showing the hover. It might be better that way so that the popup shows up via the `showHover` keybinding. Though, I also don't mind it if the commit details are shown with other stuff, since my main concern is having the details on the top if possible.

Currently, I only played around with enabling/disabling GitLens and this extension, and it does seem that GitLens always shows the commit details on the top of the hover popup. Not sure if enabling/disabling is the proper way to test it, but I'll try to look into this more as well when I find the chance (as I'm also not that familiar with VS Code extension development).

**Comment by mk12** [comment]
I'm going to close this as infeasible since I tried a few things and couldn't get it to change the order. From https://github.com/microsoft/vscode/issues/152897 and https://github.com/microsoft/vscode/issues/121930 it seems there's no officially documented way of doing this. If anyone figures out how GitLens does it, feel free to reopen and I would be happy to change it or make it configurable.
