### ISSUE TITLE
Inline annotations do not move when selecting text downwards

### ISSUE THREAD

**Issue by Arnesfield** [mk12/vscode-better-git-line-blame#16]
Selecting text downwards does not move the inline annotations.

Rather, it gets mounted on the line where the selection started instead of following the selection.

And as expected, the hover popup does not show up when it's not on the same line as the cursor.

https://github.com/user-attachments/assets/31cfcc1b-82ce-4fc1-b5ff-1dc18989950b

Also tested the inline annotations from [GitLens](https://github.com/gitkraken/vscode-gitlens) and [vscode-git-line-blame](https://github.com/carlthome/vscode-git-line-blame) extensions and they all seem to properly move the inline annotations.

It's not that big of an issue, but it may feel inconsistent if the inline annotations move when selecting upwards but not downwards.

**Comment by mk12** [comment]
Ah, i just made it always go on the top line of the selection. I see what you mean though, going to the line where the cursor is would be better. I’ll fix this in the next release.

**Comment by mk12** [comment]
Fix published in 0.2.12.
