### ISSUE TITLE
No inline blame annotations when a standalone file is opened

### ISSUE THREAD

**Issue by Arnesfield** [mk12/vscode-better-git-line-blame#18]
Opened VS Code without a project (just running `code` from the terminal), then opening a file from a git repository does not show the inline blame annotations for that file.

Seems to work for [GitLens](https://github.com/gitkraken/vscode-gitlens) but doesn't for the [vscode-git-line-blame](https://github.com/carlthome/vscode-git-line-blame) extension.

https://github.com/user-attachments/assets/067eb14c-6003-45c8-9352-80953deac82d

Also tested opening different files from different git repositories and GitLens seems to show the inline annotations properly.

Bit of an edge case really. I don't think most users would notice, but it would be nice to still have the inline annotations available.

**Comment by mk12** [comment]
The extension is designed to stay in sync with VS Code's tracking of the repository. Usually when you open a file in a git repo, there will be a dialog in the bottom right asking if you want to open the repository. You can also see at the start of your video on the left, "A Git repository was found in the parent folders of the workspace or the open file(s)." with an "Open Repository" button. If you click that, the extension should activate. If it doesn't (i.e. you can see git info in the Source Control tab but there are no annotations), then that's a bug.

**Comment by Arnesfield** [comment]
Got it, thanks!
