### ISSUE TITLE
Feature Request: Command to show commit as plain text

### ISSUE THREAD

**Issue by Arnesfield** [mk12/vscode-better-git-line-blame#19]
Currently, there is an existing command `betterGitLineBlame.showCommit` that shows a markdown preview of the commit info to the side. I'd like to request another command that more or less does the same thing but as plain text (even the same markdown source text would be fine).

My main use case is being able to copy contents of the commit info (i.e. the commit hash or message) without having to use the mouse to select the contents from either the hover popup or the markdown preview.

I've made a workaround for this via a keybinding which shows the preview for the commit info then shows the markdown source for it:

```json5
{
  "key": "alt+a",
  "command": "runCommands",
  "when": "editorTextFocus",
  "args": {
    "commands": [
      "betterGitLineBlame.showCommit",
      "markdown.showSource",
      "workbench.action.openPreviousRecentlyUsedEditor"
      // then close the markdown preview manually
    ]
  }
}
```

Hopefully it gets planned as a feature as it would be nice to have as a command so it's always consistent.

**Comment by mk12** [comment]
Published in 0.2.12.
